from src.dominio.cartas import Carta, Palo, Numero
from src.ui.style import *
NORMAS = [
    {
        "titulo": "Introducción",
        "bloques": [
            {"tipo": "titulo", "texto": "El Truque"},
            {"tipo": "texto", "texto": "El truque es un juego de cartas que usa la Baraja Española de 40 cartas."},
            {"tipo": "nueva_linea"},
            {"tipo": "texto", "texto": "Para ello, se forman "},
            {"tipo": "texto", "texto": "2 Equipos ", "color": COLOR_EQUIPO1},
            {"tipo": "texto", "texto": "de 1 a 5 jugadores."},
            {"tipo": "texto", "texto": "El objetivo principal del juego es ganar 3 juegos. Se gana un juego sumando "},
            {"tipo": "texto", "texto": "31 puntos.", "color": COLOR_TEXT_HIGH},
            {"tipo": "nueva_linea"},
            {"tipo": "texto", "texto": "Hay dos formas de obtener puntos: con la apuesta de "},
            {"tipo": "texto", "texto": "pares ", "color": COLOR_TEXT_HIGH},
            {"tipo": "texto", "texto": "y con el "},
            {"tipo": "texto", "texto": "truque.", "color": COLOR_TEXT_HIGH},
            {"tipo": "nueva_linea"},
            {"tipo": "nueva_linea"},
            {"tipo": "texto", "texto": "Al empezar la partida, se colocan los jugadores de "},
            {"tipo": "texto", "texto": "un equipo ", "color": COLOR_EQUIPO1},
            {"tipo": "texto", "texto": "intercalados con los del "},
            {"tipo": "texto", "texto": "otro.", "color": COLOR_EQUIPO2},
            {"tipo": "nueva_linea"},
            {"tipo": "texto", "texto": "El "},
            {"tipo": "texto", "texto": "jugador ", "color": COLOR_EQUIPO1},
            {"tipo": "texto", "texto": "que empieza, se llama "},
            {"tipo": "texto", "texto": "mano ", "color": COLOR_MANO},
            {"tipo": "texto", "texto": "y va cambiando en cada ronda."},
            {"tipo": "nueva_linea"},
            {"tipo": "texto", "texto": "A partir de él, juega el siguiente jugador situado a su derecha, y así sucesivamente."},
            {"tipo": "nueva_linea"},
            {"tipo": "nueva_linea"},
            {"tipo": "texto", "texto": "En cada ronda, se reparten "},
            {"tipo": "texto", "texto": "3 ", "color": COLOR_TEXT_HIGH},
            {"tipo": "texto", "texto": "cartas por jugador, y una "},
            {"tipo": "texto", "texto": "guía ", "color": COLOR_TEXT_HIGH},
            {"tipo": "texto", "texto": "en la mesa."},
            {"tipo": "nueva_linea"},
            {"tipo": "texto", "texto": "Esta "},
            {"tipo": "texto", "texto": "guía ", "color": COLOR_TEXT_HIGH},
            {"tipo": "texto", "texto": "marca el "},
            {"tipo": "texto", "texto": "palo ", "color": COLOR_TEXT_HIGH},
            {"tipo": "texto", "texto": "que manda, y el valor de cada carta cambia dependiendo de si son de este palo."},
        ]
    }, 
    {
        "titulo": "Desarrollo",
        "bloques": [
            {"tipo": "titulo", "texto": "Desarrollo del Juego"},
            {"tipo": "texto", "texto": "Al jugar la partida, cada "},
            {"tipo": "texto", "texto": "jugador ", "color": COLOR_EQUIPO1},
            {"tipo": "texto", "texto": "va echando una carta por orden."},
            {"tipo": "nueva_linea"},
            {"tipo": "texto", "texto": "Cuando todos los jugadores han echado una carta, se busca al "},
            {"tipo": "texto", "texto": "jugador ", "color": COLOR_EQUIPO1},
            {"tipo": "texto", "texto": "con la "},
            {"tipo": "texto", "texto": "carta de mas valor.", "color": COLOR_TEXT_HIGH},
            {"tipo": "nueva_linea"},
            {"tipo": "texto", "texto": "Este "},
            {"tipo": "texto", "texto": "jugador ", "color": COLOR_EQUIPO1},
            {"tipo": "texto", "texto": "es el primero en echar una nueva carta, y su equipo gana el primer "},
            {"tipo": "texto", "texto": "baza.", "color": COLOR_TEXT_HIGH},
            {"tipo": "nueva_linea"},
            {"tipo": "texto", "texto": "El primer equipo que gane dos bazas, gana el "},
            {"tipo": "texto", "texto": "truque.", "color": COLOR_TEXT_HIGH},
            {"tipo": "nueva_linea"},
            {"tipo": "nueva_linea"},
            {"tipo": "texto", "texto": "Durante la primera baza, hacen las "},
            {"tipo": "texto", "texto": "apuestas de pares ", "color": COLOR_TEXT_HIGH},
            {"tipo": "texto", "texto": "o se "},
            {"tipo": "texto", "texto": "cantan las flores.", "color": COLOR_TEXT_HIGH},
            {"tipo": "nueva_linea"},
            {"tipo": "texto", "texto": "Una vez realizadas esas apuestas, se puede "},
            {"tipo": "texto", "texto": "trucar, ", "color": COLOR_TEXT_HIGH},
            {"tipo": "texto", "texto": "es decir, apostar al "},
            {"tipo": "texto", "texto": "equipo ", "color": COLOR_EQUIPO1},
            {"tipo": "texto", "texto": "que va a ganar el truque."},
            {"tipo": "nueva_linea"},
            {"tipo": "texto", "texto": "Una vez que se han ganado 2 bazas, o no se ha querido ninguna apuesta, se hace el recuento de puntos."},
            {"tipo": "nueva_linea"},
            {"tipo": "nueva_linea"},
            {"tipo": "texto", "texto": "Si en la primera baza hay "},
            {"tipo": "texto", "texto": "dos cartas con el mismo valor ", "color": COLOR_TEXT_HIGH},
            {"tipo": "texto", "texto": "se ha hecho "},
            {"tipo": "texto", "texto": "pata.", "color": COLOR_TEXT_HIGH},
            {"tipo": "nueva_linea"},
            {"tipo": "texto", "texto": "En este caso, cada "},
            {"tipo": "texto", "texto": "jugador ", "color": COLOR_EQUIPO1},
            {"tipo": "texto", "texto": "empezando por la "},
            {"tipo": "texto", "texto": "mano ", "color": COLOR_MANO},
            {"tipo": "texto", "texto": "echa una carta."},
            {"tipo": "nueva_linea"},
            {"tipo": "texto", "texto": "El "},
            {"tipo": "texto", "texto": "equipo ", "color": COLOR_EQUIPO1},
            {"tipo": "texto", "texto": "con la mejor carta gana el "},
            {"tipo": "texto", "texto": "truque.", "color": COLOR_TEXT_HIGH},
        ]
    }, 
    {
        "titulo": "Orden Cartas",
        "bloques": [
            {"tipo": "titulo", "texto": "Orden de las cartas"},
            {"tipo": "texto", "texto": "Cada carta, tiene un valor dependiendo de si es "},
            {"tipo": "texto", "texto": "guía ", "color": COLOR_TEXT_HIGH},
            {"tipo": "texto", "texto": "o no."},
            {"tipo": "nueva_linea"},
            {"tipo": "texto", "texto": "Las cartas son "},
            {"tipo": "texto", "texto": "guía ", "color": COLOR_TEXT_HIGH},
            {"tipo": "texto", "texto": "si su palo coincide con el de la "},
            {"tipo": "texto", "texto": "guía en la mesa.", "color": COLOR_TEXT_HIGH},
            {"tipo": "nueva_linea"},
            {"tipo": "texto", "texto": "Además, "},
            {"tipo": "carta", "carta": Carta(Numero.AS, Palo.COPAS)},
            {"tipo": "carta", "carta": Carta(Numero.AS, Palo.OROS)},
            {"tipo": "texto", "texto": " siempre ", "color": COLOR_TEXT_HIGH},
            {"tipo": "texto", "texto": "son guía, y el "},
            {"tipo": "texto", "texto": "6 y 7 ", "color": COLOR_TEXT_HIGH},
            {"tipo": "texto", "texto": "del palo de la guía "},
            {"tipo": "texto", "texto": "no se consideran guía.", "color": COLOR_TEXT_HIGH},
            {"tipo": "nueva_linea"},
            {"tipo": "texto", "texto": "El 4 de la guía vale exactamente lo mismo que "},
            {"tipo": "texto", "texto": "guía en la mesa", "color": COLOR_TEXT_HIGH},
            {"tipo": "texto", "texto": ", salvo que sean el 6 o 7."},
            {"tipo": "nueva_linea"},
            {"tipo": "texto", "texto": "Por ejemplo, si es guía "},
            {"tipo": "carta", "carta": Carta(Numero.AS, Palo.OROS)},
            {"tipo": "texto", "texto": " el jugador que tenga el "},
            {"tipo": "carta", "carta": Carta(Numero.CUATRO, Palo.OROS)},
            {"tipo": "texto", "texto": "lo podrá usar exactamente como si fuera el As."},
            {"tipo": "nueva_linea"},
            {"tipo": "nueva_linea"},
            {"tipo": "texto", "texto": "De esta forma, el valor de las cartas es: primero el "},
            {"tipo": "texto", "texto": "3, 2 y 5 de la guía", "color": COLOR_TEXT_HIGH},
            {"tipo": "texto", "texto": ", en ese orden."},
            {"tipo": "nueva_linea"},
            {"tipo": "texto", "texto": "Luego "},
            {"tipo": "carta", "carta": Carta(Numero.AS, Palo.COPAS)},
            {"tipo": "carta", "carta": Carta(Numero.AS, Palo.OROS)},
            {"tipo": "texto", "texto": "independiente de la guía que pinte. Después el "},
            {"tipo": "texto", "texto": "As, Rey, Espada y Sota de la guía", "color": COLOR_TEXT_HIGH},
            {"tipo": "nueva_linea"},
            {"tipo": "texto", "texto": "A continuación "},
            {"tipo": "carta", "carta": Carta(Numero.AS, Palo.ESPADAS)},
            {"tipo": "carta", "carta": Carta(Numero.AS, Palo.BASTOS)},
            {"tipo": "carta", "carta": Carta(Numero.SIETE, Palo.ESPADAS)},
            {"tipo": "carta", "carta": Carta(Numero.SIETE, Palo.OROS)},
            {"tipo": "texto", "texto": " y por último las cartas que no son de la guía, ordenadas por "},
            {"tipo": "texto", "texto": "3, 2, Rey, Caballo, Sota, 7, 6, 5, 4", "color": COLOR_TEXT_HIGH},
            {"tipo": "nueva_linea"},
            {"tipo": "nueva_linea"},
            {"tipo": "texto", "texto": "Si la guía es "},
            {"tipo": "carta", "carta": Carta(Numero.CABALLO, Palo.COPAS)},
            {"tipo": "texto", "texto": " el orden de las cartas es: "},
            {"tipo": "carta", "carta": Carta(Numero.TRES, Palo.COPAS)},
            {"tipo": "carta", "carta": Carta(Numero.DOS, Palo.COPAS)},
            {"tipo": "carta", "carta": Carta(Numero.CINCO, Palo.COPAS)},
            {"tipo": "carta", "carta": Carta(Numero.AS, Palo.COPAS)},
            {"tipo": "carta", "carta": Carta(Numero.AS, Palo.OROS)},
            {"tipo": "carta", "carta": Carta(Numero.REY, Palo.COPAS)},
            {"tipo": "carta", "carta": Carta(Numero.CUATRO, Palo.COPAS)},
            {"tipo": "carta", "carta": Carta(Numero.SOTA, Palo.COPAS)},
            {"tipo": "carta", "carta": Carta(Numero.AS, Palo.ESPADAS)},
            {"tipo": "carta", "carta": Carta(Numero.AS, Palo.BASTOS)},
            {"tipo": "carta", "carta": Carta(Numero.SIETE, Palo.ESPADAS)},
            {"tipo": "carta", "carta": Carta(Numero.SIETE, Palo.OROS)},
            {"tipo": "carta", "carta": Carta(Numero.TRES, Palo.BASTOS)},
            {"tipo": "carta", "carta": Carta(Numero.DOS, Palo.BASTOS)},
            {"tipo": "carta", "carta": Carta(Numero.REY, Palo.BASTOS)},
            {"tipo": "carta", "carta": Carta(Numero.CABALLO, Palo.BASTOS)},
            {"tipo": "carta", "carta": Carta(Numero.SOTA, Palo.BASTOS)},
            {"tipo": "carta", "carta": Carta(Numero.SIETE, Palo.BASTOS)},
            {"tipo": "carta", "carta": Carta(Numero.SEIS, Palo.BASTOS)},
            {"tipo": "carta", "carta": Carta(Numero.CINCO, Palo.BASTOS)},
            {"tipo": "carta", "carta": Carta(Numero.CUATRO, Palo.BASTOS)},
        ]
    },
    {
        "titulo": "Truque",
        "bloques": [
            {"tipo": "titulo", "texto": "Apuesta de Truque"},
            {"tipo": "texto", "texto": "A lo largo de la partida, un "},
            {"tipo": "texto", "texto": "jugador ", "color": COLOR_EQUIPO1},
            {"tipo": "texto", "texto": "puede '"},
            {"tipo": "texto", "texto": "trucar", "color": COLOR_TEXT_HIGH},
            {"tipo": "texto", "texto": "', es decir, apostar a que su "},
            {"tipo": "texto", "texto": "equipo ", "color": COLOR_EQUIPO1},
            {"tipo": "texto", "texto": "gana el "},
            {"tipo": "texto", "texto": "truque.", "color": COLOR_TEXT_HIGH},
            {"tipo": "nueva_linea"},
            {"tipo": "texto", "texto": "El "},
            {"tipo": "texto", "texto": "otro equipo ", "color": COLOR_EQUIPO2},
            {"tipo": "texto", "texto": "puede el elegir si "},
            {"tipo": "texto", "texto": "querer o rechazar ", "color": COLOR_TEXT_HIGH},
            {"tipo": "texto", "texto": "la el truque:"},
            {"tipo": "nueva_linea"},
            {"tipo": "texto", "texto": "Si "},
            {"tipo": "texto", "texto": "un jugador ", "color": COLOR_EQUIPO2},
            {"tipo": "texto", "texto": "quiere ", "color": COLOR_TEXT_HIGH},
            {"tipo": "texto", "texto": "la apuesta de truque, al final de la ronda "},
            {"tipo": "texto", "texto": "equipo que gane el truque ", "color": COLOR_TEXT_HIGH},
            {"tipo": "texto", "texto": "se lleva "},
            {"tipo": "texto", "texto": "3 puntos.", "color": COLOR_TEXT_HIGH},
            {"tipo": "nueva_linea"},
            {"tipo": "texto", "texto": "Si "},
            {"tipo": "texto", "texto": "todos los jugadores ", "color": COLOR_EQUIPO2},
            {"tipo": "texto", "texto": "rechazan ", "color": COLOR_TEXT_HIGH},
            {"tipo": "texto", "texto": "el truque "},
            {"tipo": "texto", "texto": "equipo que trucó ", "color": COLOR_EQUIPO1},
            {"tipo": "texto", "texto": "se lleva directamente "},
            {"tipo": "texto", "texto": "1 punto ", "color": COLOR_TEXT_HIGH},
            {"tipo": "texto", "texto": "y se acaba la ronda."},
            {"tipo": "nueva_linea"},
            {"tipo": "nueva_linea"},
            {"tipo": "texto", "texto": "Si un "},
            {"tipo": "texto", "texto": "equipo ", "color": COLOR_EQUIPO1},
            {"tipo": "texto", "texto": "ya ha trucado, el "},
            {"tipo": "texto", "texto": "otro equipo ", "color": COLOR_EQUIPO2},
            {"tipo": "texto", "texto": "puede "},
            {"tipo": "texto", "texto": "retrucar ", "color": COLOR_TEXT_HIGH},
            {"tipo": "texto", "texto": "es decir, subir la apuesta a "},
            {"tipo": "texto", "texto": "6 puntos.", "color": COLOR_TEXT_HIGH},
            {"tipo": "nueva_linea"},
            {"tipo": "texto", "texto": "Si ya se ha "},
            {"tipo": "texto", "texto": "retrucado ", "color": COLOR_EQUIPO2},
            {"tipo": "texto", "texto": "el "},
            {"tipo": "texto", "texto": "otro equipo ", "color": COLOR_EQUIPO1},
            {"tipo": "texto", "texto": "puede echar "},
            {"tipo": "texto", "texto": "Juego Fuera ", "color": COLOR_TEXT_HIGH},
            {"tipo": "texto", "texto": "es decir, quien gane el truque, "},
            {"tipo": "texto", "texto": "gana la partida.", "color": COLOR_TEXT_HIGH},
        ]
    },
    {
        "titulo": "Pares",
        "bloques": [
            {"tipo": "titulo", "texto": "Apuesta de Pares"},
            {"tipo": "texto", "texto": "Al principio de cada ronda, se puede hacer una apuesta de "},
            {"tipo": "texto", "texto": "pares.", "color": COLOR_TEXT_HIGH},
            {"tipo": "nueva_linea"},
            {"tipo": "texto", "texto": "Para ello, un jugador puede "},
            {"tipo": "texto", "texto": "envidar", "color": COLOR_TEXT_HIGH},
            {"tipo": "texto", "texto": ", es decir, apostar un número de puntos a qué "},
            {"tipo": "texto", "texto": "equipo ", "color": COLOR_EQUIPO1},
            {"tipo": "texto", "texto": "tiene más pares."},
            {"tipo": "nueva_linea"},
            {"tipo": "texto", "texto": "La apuesta máxima es "},
            {"tipo": "texto", "texto": "la falta", "color": COLOR_TEXT_HIGH},
            {"tipo": "texto", "texto": ", que es el número de puntos que le falta al "},
            {"tipo": "texto", "texto": "equipo ", "color": COLOR_EQUIPO1},
            {"tipo": "texto", "texto": "que va ganando para llegar a 31."},
            {"tipo": "nueva_linea"},
            {"tipo": "texto", "texto": "Por ejemplo, si la puntuación actual es "},
            {"tipo": "texto", "texto": "12 ", "color": COLOR_EQUIPO1},
            {"tipo": "texto", "texto": "a "},
            {"tipo": "texto", "texto": "28", "color": COLOR_EQUIPO2},
            {"tipo": "texto", "texto": ", la apuesta máxima (la falta) será de "},
            {"tipo": "texto", "texto": "3 puntos.", "color": COLOR_TEXT_HIGH},
            {"tipo": "nueva_linea"},
            {"tipo": "nueva_linea"},
            {"tipo": "texto", "texto": "Cuando se "},
            {"tipo": "texto", "texto": "hace una apuesta ", "color": COLOR_EQUIPO1},
            {"tipo": "texto", "texto": "el "},
            {"tipo": "texto", "texto": "equipo contrario ", "color": COLOR_EQUIPO2},
            {"tipo": "texto", "texto": "puede querer, rechazar o resubir la apuesta:"},
            {"tipo": "nueva_linea"},
            {"tipo": "texto", "texto": "Si un "},
            {"tipo": "texto", "texto": "jugador ", "color": COLOR_EQUIPO2},
            {"tipo": "texto", "texto": "quiere la apuesta, el equipo que tenga mejores pares suma los puntos al final de la ronda."},
            {"tipo": "nueva_linea"},
            {"tipo": "texto", "texto": "Si un "},
            {"tipo": "texto", "texto": "jugador ", "color": COLOR_EQUIPO2},
            {"tipo": "texto", "texto": "resube la apuesta, ahora es el otro "},
            {"tipo": "texto", "texto": "equipo ", "color": COLOR_EQUIPO1},
            {"tipo": "texto", "texto": "el que puede querer, rechazar o resubir."},
            {"tipo": "nueva_linea"},
            {"tipo": "texto", "texto": "Si todos los "},
            {"tipo": "texto", "texto": "jugadores ", "color": COLOR_EQUIPO2},
            {"tipo": "texto", "texto": "rechazan la apuesta, el "},
            {"tipo": "texto", "texto": "equipo que ha apostado ", "color": COLOR_EQUIPO1},
            {"tipo": "texto", "texto": "se lleva 1 punto. (O todas las apuestas anteriores aceptadas.)"},
            {"tipo": "nueva_linea"},
            {"tipo": "texto", "texto": "Por ejemplo, el "},
            {"tipo": "texto", "texto": "primer equipo ", "color": COLOR_EQUIPO1},
            {"tipo": "texto", "texto": "envida ", "color": COLOR_TEXT_HIGH},
            {"tipo": "texto", "texto": "(apuesta 2), y el "},
            {"tipo": "texto", "texto": "otro equipo ", "color": COLOR_EQUIPO2},
            {"tipo": "texto", "texto": "resube la apuesta a "},
            {"tipo": "texto", "texto": "5. ", "color": COLOR_TEXT_HIGH},
            {"tipo": "texto", "texto": "Si el "},
            {"tipo": "texto", "texto": "equipo ", "color": COLOR_EQUIPO1},
            {"tipo": "texto", "texto": "no quiere la apuesta, el "},
            {"tipo": "texto", "texto": "segundo equipo ", "color": COLOR_EQUIPO2},
            {"tipo": "texto", "texto": "se lleva los "},
            {"tipo": "texto", "texto": "2 puntos.", "color": COLOR_TEXT_HIGH},
        ]
    },
    {
        "titulo": "sgf",
        "bloques": [
            {"tipo": "titulo", "texto": "Apuesta de Pares"},
            {"tipo": "texto", "texto": "que va ganando para llegar a 31."},
        ]
    }
]